services:
  - type: web
    name: quiz-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    disk:
      name: db
      mountPath: /opt/render/project/data
      sizeGB: 1